version: "3"
services:
  web:
    image: antihero/blitcc-web:latest
    ports:
      - "1337:80"
    restart: always
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: always
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANINTERVAL: 1m
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/var/navidrome:/data"
      - "/var/music:/music:ro"
