apiVersion: apps/v1
kind: Deployment
metadata:
  name: blit-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blit-web
  template:
    metadata:
      labels:
        app: blit-web
    spec:
      containers:
        - name: blit-web
          image: antihero/blitcc-web
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-vol
spec:
  capacity:
    storage: 400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/music
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - soul
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-vol
spec:
  capacity:
    storage: 400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/navidrome
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - soul
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: navidrome
spec:
  serviceName: "navidrome"
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
        - name: navidrome
          image: deluan/navidrome
          volumeMounts:
            - name: music-vol
              mountPath: /music
            - name: navidrome-vol
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: music-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-storage"
        resources:
          requests:
            storage: 400Gi
    - metadata:
        name: navidrome-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-storage"
        resources:
          requests:
            storage: 40Gi
---
apiVersion: v1
kind: Service
metadata:
  name: blit-web
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: blit-web
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
spec:
  ports:
    - port: 80
      targetPort: 4533
  selector:
    app: navidrome
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blit-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  rules:
    - host: blit.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blit-web
                port:
                  number: 80
    - host: nd.blit.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  number: 80
