/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LanguageTagIndexRouteImport } from './routes/$languageTag/index'
import { Route as LanguageTagCvRouteImport } from './routes/$languageTag/cv'

const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageTagIndexRoute = LanguageTagIndexRouteImport.update({
  id: '/$languageTag/',
  path: '/$languageTag/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageTagCvRoute = LanguageTagCvRouteImport.update({
  id: '/$languageTag/cv',
  path: '/$languageTag/cv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/$languageTag/cv': typeof LanguageTagCvRoute
  '/$languageTag': typeof LanguageTagIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/$languageTag/cv': typeof LanguageTagCvRoute
  '/$languageTag': typeof LanguageTagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/$languageTag/cv': typeof LanguageTagCvRoute
  '/$languageTag/': typeof LanguageTagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cv' | '/$languageTag/cv' | '/$languageTag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cv' | '/$languageTag/cv' | '/$languageTag'
  id: '__root__' | '/' | '/cv' | '/$languageTag/cv' | '/$languageTag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  LanguageTagCvRoute: typeof LanguageTagCvRoute
  LanguageTagIndexRoute: typeof LanguageTagIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageTag/': {
      id: '/$languageTag/'
      path: '/$languageTag'
      fullPath: '/$languageTag'
      preLoaderRoute: typeof LanguageTagIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$languageTag/cv': {
      id: '/$languageTag/cv'
      path: '/$languageTag/cv'
      fullPath: '/$languageTag/cv'
      preLoaderRoute: typeof LanguageTagCvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  LanguageTagCvRoute: LanguageTagCvRoute,
  LanguageTagIndexRoute: LanguageTagIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
