name: Deploy web to AWS

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: radiosilence/blit-web/.github/workflows/deploy-ami-aws.yml@main
    with:
      tf_cloud_organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
      tf_workspace: "blit-web"
      tf_config_directory: "./web/terraform"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
