name: Deploy web to AWS

permissions:
  contents: read

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  CONFIG_DIRECTORY: "./web/terraform"

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Set up OPS
        run: curl https://ops.city/get.sh -sSfL | sh
      - name: Set OPS environment variables
        run: |
          echo "OPS_DIR=$HOME/.ops" >> $GITHUB_ENV
          echo "$HOME/.ops/bin" >> $GITHUB_PATH
      - uses: oven-sh/setup-bun@v1
      - name: Create AMI
        run: |
          cd web
          echo PATH=$PATH
          echo OPS_DIR=$OPS_DIR
          make image-create-aws
      - name: Set AMI ID
        run: |
          cd web
          make image-get-aws | jq
          AMI_ID=$(echo $(make image-get-aws) | jq -r '.ID')
          echo "TF_VAR_ami_id=\"$AMI_ID\"" >> $GITHUB_ENV
      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: apply-upload
        with:
          workspace: ${{ vars.TF_WORKSPACE_BLIT_WEB }}
          directory: ${{ env.CONFIG_DIRECTORY }}
      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ vars.TF_WORKSPACE_BLIT_WEB }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}
      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
