name: Deploy web to AWS

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up OPS
        run: |
          curl https://ops.city/get.sh -sSfL | sh
      - name: Create AMI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export OPS_DIR="$HOME/.ops"
          export PATH="$HOME/.ops/bin:$PATH"
          cd web
          make image-create-aws
      - name: Echo AMI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export OPS_DIR="$HOME/.ops"
          export PATH="$HOME/.ops/bin:$PATH"
          cd web
          make get-image-aws
          echo "TODO: Run TF deployment with this image using TF cloud"
