name: K8s Deploy/Update

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "k8s/**"
      - "web/**"

jobs:
  apply-blit:
    name: apply blit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: apply blit
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f k8s/blit.yml
  apply-letsencrypt-prod:
    name: apply letsencrypt-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: apply letsencrypt prod
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f k8s/letsencrypt-prod.yml
  rollout-blit-web:
    name: rollout blit-web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout restart deployment/blit-web --namespace blit

  rollout-navidrome:
    name: rollout navidrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: restart statefulset
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout restart statefulset/navidrome --namespace blit
