name: Publish Blit Web Container

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - "./**"
  pull_request:

jobs:
  publish-web:
    uses: radiosilence/blit-workflows/.github/workflows/build-publish-container.yml@main
    with:
      working-directory: "."
    secrets:
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}
