name: Publish Web Container

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - seed
    tags:
      - v*
  pull_request:

jobs:
  publish-web:
    uses: radiosilence/blit-workflows/.github/workflows/build-publish-container.yml@main
    with:
      working_directory: "./web"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
