name: Publish Blit Web Container

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    paths:
      - "**"
  pull_request:

jobs:
  publish-web:
    uses: radiosilence/blit-workflows/.github/workflows/build-publish-container.yml@main
    with:
      working-directory: "."
    secrets:
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  deploy-web:
    runs-on: ubuntu-latest
    needs: publish-web
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout jaritanet architecture repo
        uses: actions/checkout@v4
        with:
          repository: radiosilence/jaritanet
          token: ${{ secrets.GITHUB_TOKEN }}
          path: jaritanet

      - name: Update blit service tag in Pulumi config
        run: |
          SHORT_SHA="sha-$(echo ${{ github.sha }} | cut -c1-7)"

          # Use yq to update the blit service tag
          yq eval '(.config."jaritanet-k8s:services"[] | select(.name == "blit") | .args.image.tag) = "'$SHORT_SHA'"' -i jaritanet/packages/k8s/Pulumi.main.yaml

      - name: Commit and push changes
        run: |
          cd jaritanet
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/k8s/Pulumi.main.yaml
          git commit -m "Update blit service tag to sha-$(echo ${{ github.sha }} | cut -c1-7)"
          git push
