name: Build and Deploy Blit

env:
  PROJECT_NAME: blit
  ACCOUNT: radiosilence
  DEPLOYMENT_REPO: jaritanet
  DEPLOYMENT_BRANCH: main
  DEPLOYMENT_CONFIG_PATH: packages/k8s/Pulumi.main.yaml

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    paths:
      - "**"
  pull_request:

jobs:
  build-and-publish:
    uses: radiosilence/blit-workflows/.github/workflows/build-publish-container.yml@main
    with:
      working-directory: "."
    secrets:
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  update-deployment:
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: github.ref == 'refs/heads/main'

    env:
      SHORT_SHA: sha-${{ github.sha }}

    steps:
      - name: Checkout deployment repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ACCOUNT }}/${{ env.DEPLOYMENT_REPO }}
          ref: ${{ env.DEPLOYMENT_BRANCH }}
          token: ${{ secrets.DEPLOYMENT_PAT }}
          path: ${{ env.DEPLOYMENT_REPO }}

      - name: Update service tag in deployment config
        run: |
          SHORT_SHA_TRIMMED="${{ env.SHORT_SHA }}"
          SHORT_SHA_TRIMMED=${SHORT_SHA_TRIMMED:0:11}

          yq eval \
            '(.config."jaritanet-k8s:services"[] | select(.name == "${{ env.PROJECT_NAME }}") | .args.image.tag) = "'$SHORT_SHA_TRIMMED'"' \
            -i ${{ env.DEPLOYMENT_REPO }}/${{ env.DEPLOYMENT_CONFIG_PATH }}

      - name: Commit and push deployment update
        run: |
          cd ${{ env.DEPLOYMENT_REPO }}

          SHORT_SHA_TRIMMED="${{ env.SHORT_SHA }}"
          SHORT_SHA_TRIMMED=${SHORT_SHA_TRIMMED:0:11}

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add ${{ env.DEPLOYMENT_CONFIG_PATH }}
          git commit -m "🚀 Update ${{ env.PROJECT_NAME }} service to $SHORT_SHA_TRIMMED"
          git push
